### ISSUE TITLE
review continuous development settings

### ISSUE THREAD

**Issue by AlbinaMuzafarova** [pik-copan/pycopancore#158]
## Description

As there are many contributors to the project, it may make sense to review the current merge workflow and understand whether it is eliminating the risk for unfinished and breaking changes to be merged into main.

## Todo

- [ ] assess current development practice
- [ ] check available options from github
- [ ] match the best possible option after discussion with the team
- [ ] update the settings, if needed

cc @mensch72 @leander-j

**Comment by AlbinaMuzafarova** [comment]
After a quick review of closed PRs, the following can be observed:

- PRs are often not linked to issues explicitly
- PRs do not have reviewers assigned
- Testers merge the PR (instead of authors)
- No checks performed to avoid breaking changes

Github provides many [options](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) for branch protection. Below an overview:

| Option  | Description | Recommendation |
| ------------- | ------------- |:---: |
| PR review before merge  | Unless 1 or more reviews validate the PR, it cannot be merged. Stale approvals can be missmissed. Blocking reviews can be dismissed.  | +  |
| Status checks before merge  | Unless uptodate with target, PR cannot be merged (`Strict` mode) | +  |
| Conversation resolution  before merge  | As long as unresolved conversations, PR cannot be merged  | +  |
| Signed commits  | Verified commits only  | - |
| Linear history  | All commits squashed before merge  | -  |
| Merge queue  | Limited to public beta and subject to change  | - |
| Include admins | Users with admin accounts must receive validation before merging their PRs | +  |
| Restricted push  | Available for repositories owned by an organization using GitHub Team or GitHub Enterprise Cloud | -  |
| Allow force pushes  | Force push allowed despite missing reviews or failed status checks  | -  |
| Allow deletion  | Protected branch can be deleted  | -  |

I would suggest to protect the `main` from direct changes, although the actively contributing team changes in size.

**Comment by AlbinaMuzafarova** [comment]
@mensch72 assigning this to you for revision.

**Comment by mensch72** [comment]
I have set the branch protection rules for "master" according to your recommendations above. But I don't understand the "status checks" procedure:
![image](https://user-images.githubusercontent.com/22815964/146174652-7ac56386-095f-44bc-a773-8f382e449c0f.png)
If I follow that link, I get to a page describing a REST API, which doesn't contain the string "status check" at all...

**Comment by AlbinaMuzafarova** [comment]
@mensch72 i will check out the details of the implementation for status checks and let you know if there's anything we should configure something ourselves there

**Comment by AlbinaMuzafarova** [comment]
@mensch72 after a quick research it looks like we need to add ourselves a `.yml` file under `.github/workflows/` where we'd specify the type of checks to be performed. Some example projects have checks for compliance with lint or other code styles; some even check whether the sphinx generates successfully the documentation. 

I can compile a first set of suggestions for checks in a separate issue. It can then be expanded/adapted, when necessary
