### ISSUE TITLE
lpjml coupling

### ISSUE THREAD

**Issue by jnnsbrr** [pik-copan/pycopancore#169]
@jdonges @mensch72 @Luana? @Werner?
On the lpjml side Werner and I made some progress in

- [x] implement an interface for coupling (via sockets) by Werner
- [x] provide a Demo how to couple LPJmL with copan including a Python Demo by Werner
- [x] provide a `LpjmlConfig` class to parse, read, set and write lpjml config files for corresponding LPJmL runs by @jnnsbrr 

still pending (to be implemented soon)
- [ ] more convenience set methods for `LpjmlConfig`
- [ ] `submit_spinup` function to submit spin-up runs for LPJmL (mandatory before actual coupled run with copan:core)

The progress can currently be viewed [here](https://gitlab.pik-potsdam.de/lpjml/LPJmL_internal/-/tree/lpjml53_copan) for those who have access.  
Beyond that, we should arrange a meeting for the next steps.

**Comment by jnnsbrr** [comment]
Recently the Python implementation of a coupling interface, described above, has been separated from the LPJmL model. It is now available [here](https://gitlab.pik-potsdam.de/lpjml/pycoupler) - if you do not have access, please write to [Werner](mailto:bloh@pik-potsdam.de)  

**Tasks left**
* [ ]  finish Python package implementation (to be able to install it)
* [ ]  add read/write data methods for the [coupler class](https://gitlab.pik-potsdam.de/lpjml/pycoupler/-/blob/main/pycoupler/coupler.py)
* [ ] test/debug coupling
* [ ] extends get methods for available LPJmL outputs with description for each
* [ ] implement `submit_couple` function analogously to [`submit_lpjml`](https://gitlab.pik-potsdam.de/lpjml/pycoupler/-/blob/main/pycoupler/submit.py)
* [ ] add interactive option for  `submit_couple` to run both coupled models interactively instead of submitting it to PIK cluster

**Comment by jnnsbrr** [comment]
ok [**pycoupler**](https://gitlab.pik-potsdam.de/lpjml/pycoupler) should be ready for use, yeay :-) 
I checked the checkboxes from the last comment of what was to be done.

Just noticed that there is one checkbox left to add a method for the available outputs to return the description for each. I will do that soon.

**Comment by sieben-gea** [comment]
I think we can close this, as the model has been implemented in [PIK-copan/pycopanlpjml](https://github.com/PIK-copan/pycopanlpjml). Reopen if necessary.
